import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { db, toJson } from "@/server/db";
import { DEFAULT_RUN_LIMITS } from "@/server/domain/blueprint";
import { AppError } from "@/server/errors";
import { llm } from "@/server/models";
import type { ChatMessage } from "@/server/models/types";
import { cancelRun, claimNextRun, executeRun, RunOutputSchema } from "@/server/runtime";
import { createTestOrg } from "../helpers/factory";
import { createHiredWorker, makeBlueprint } from "../helpers/fixtures";
import { activityTypes, checkpointOf, enqueue, kindsOf, loadRun, stepsOf, type TestOrg } from "./helpers";

/** The analyst is the first agent whose initial message carries the collected records. */
function isAnalystTurn(req: { messages: ChatMessage[] }): boolean {
  const first = req.messages[0];
  return first?.role === "user" && first.content.includes("## records");
}

describe("runtime: executeRun — full simulated run", () => {
  let t: TestOrg;
  beforeAll(async () => {
    t = await createTestOrg("rt-execute");
  });
  afterAll(async () => {
    await t.cleanup();
  });

  it("drives a hired worker end to end: deliverable, steps of every kind, linked model/tool calls, cost, evaluation, activity", async () => {
    const hired = await createHiredWorker(t.organization.id);
    const runId = await enqueue(t, hired, { instructions: ["Focus on vector databases"] });

    const outcome = await executeRun(runId);
    expect(outcome.status).toBe("SUCCEEDED");
    if (outcome.status !== "SUCCEEDED") return;
    expect(outcome.deliverableIds).toHaveLength(1);

    const run = await loadRun(runId);
    expect(run.status).toBe("SUCCEEDED");
    expect(run.lockedBy).toBeNull();
    expect(run.heartbeatAt).toBeNull();
    expect(run.error).toBeNull();
    expect(run.attempt).toBe(1);
    expect(run.finishedAt).not.toBeNull();
    expect(Number(run.costUsd)).toBeGreaterThan(0);
    expect(run.inputTokens).toBeGreaterThan(0);
    expect(run.durationMs).toBeGreaterThan(0);

    // Deliverable: rendered markdown with the records behind it.
    const deliverable = await db.deliverable.findUniqueOrThrow({ where: { id: outcome.deliverableIds[0] } });
    expect(deliverable).toMatchObject({ organizationId: t.organization.id, runId, workerId: hired.worker.id, workerVersionId: hired.version.id, jobId: hired.job.id, format: "MARKDOWN", status: "PENDING_REVIEW" });
    expect(deliverable.title).toMatch(/^Weekly AI Infra Funding Report — \d{4}-\d{2}-\d{2}$/);
    expect(deliverable.content).toContain("# Weekly AI Infra Funding Report");
    expect(deliverable.content).toContain("## Summary");
    expect(deliverable.content).toContain("## Top rounds");
    expect(deliverable.content).toContain("## Methodology");
    expect(deliverable.content).toContain(`Generated by ${hired.worker.name}`);
    expect(Array.isArray(deliverable.data)).toBe(true);
    const records = deliverable.data as Array<Record<string, unknown>>;
    expect(records.length).toBeGreaterThanOrEqual(8);
    for (const r of records) {
      expect(typeof r.company).toBe("string");
      expect(r.rank).toEqual(expect.any(Number));
    }
    expect(deliverable.summary?.length).toBeGreaterThan(20);

    // Run output summary follows the documented shape.
    const output = RunOutputSchema.parse(run.output);
    expect(output.summary).toMatch(new RegExp(`^Produced “${deliverable.title}” \\(${records.length} records\\) in \\d+ steps$`));
    expect(output.deliverableIds).toEqual([deliverable.id]);
    expect(output.stats.modelCalls).toBeGreaterThan(0);
    expect(output.stats.toolCalls).toBeGreaterThan(0);

    // Steps: one of each kind we expect, monotonic indexes, all closed.
    const steps = await stepsOf(runId);
    expect(steps.map((s) => s.index)).toEqual(steps.map((_, i) => i));
    const kinds = kindsOf(steps);
    for (const kind of ["MODEL_CALL", "TOOL_CALL", "DETERMINISTIC", "DELIVERABLE", "EVALUATION"] as const) expect(kinds.has(kind)).toBe(true);
    expect(kinds.has("ERROR")).toBe(false);
    expect(kinds.has("APPROVAL")).toBe(false);
    expect(steps.every((s) => s.status === "SUCCEEDED" && s.finishedAt !== null && s.attempt === 1)).toBe(true);
    const modelSteps = steps.filter((s) => s.kind === "MODEL_CALL");
    expect(modelSteps[0].title).toBe(`${hired.worker.name} is thinking (Researcher, turn 1)`);
    expect(modelSteps[0].componentId).toBe("collector");
    expect(modelSteps.at(-1)?.componentId).toBe("analyst");
    const deterministicNames = steps.filter((s) => s.kind === "DETERMINISTIC").map((s) => s.title);
    expect(deterministicNames).toEqual(["Validate records", "Remove duplicates", "Rank by round size", "Compile report"]);
    expect(steps.find((s) => s.kind === "DELIVERABLE")?.title).toBe(`Delivered “${deliverable.title}”`);
    expect(steps.find((s) => s.kind === "EVALUATION")?.title).toBe("Evaluating the deliverable");
    expect(steps.at(-1)?.kind).toBe("EVALUATION");

    // Model calls are linked to their MODEL_CALL step and attributed to the run.
    const modelCalls = await db.modelCall.findMany({ where: { runId, purpose: "agent.turn" } });
    expect(modelCalls.length).toBe(modelSteps.length);
    const modelStepIds = new Set(modelSteps.map((s) => s.id));
    for (const call of modelCalls) {
      expect(call.runStepId && modelStepIds.has(call.runStepId)).toBe(true);
      expect(call).toMatchObject({ organizationId: t.organization.id, workerId: hired.worker.id, jobId: hired.job.id, simulated: true });
    }
    // The judge's call is attributed too, but to no step of its own.
    expect(await db.modelCall.count({ where: { runId, purpose: "evaluation.judge" } })).toBe(1);

    // Tool calls are linked to their TOOL_CALL step.
    const toolCalls = await db.toolCall.findMany({ where: { runId } });
    const toolStepIds = new Set(steps.filter((s) => s.kind === "TOOL_CALL").map((s) => s.id));
    expect(toolCalls.length).toBe(toolStepIds.size);
    for (const call of toolCalls) {
      expect(call.runStepId && toolStepIds.has(call.runStepId)).toBe(true);
      expect(call).toMatchObject({ status: "SUCCEEDED", attempt: 1, workerId: hired.worker.id, simulated: true });
      expect(call.callId).toMatch(/^mock_\d+_\d+$/);
      expect(call.output).not.toBeNull();
    }
    expect(new Set(toolCalls.map((c) => c.toolName))).toEqual(new Set(["web_search", "fetch_url", "extract_data"]));

    // Evaluation ran (both rows) and the worker was refreshed.
    const evaluations = await db.evaluation.findMany({ where: { runId } });
    expect(evaluations.map((e) => e.type).sort()).toEqual(["DETERMINISTIC", "LLM_JUDGE"]);
    const worker = await db.worker.findUniqueOrThrow({ where: { id: hired.worker.id } });
    expect(worker.lastRunAt).not.toBeNull();
    expect(worker.score).not.toBeNull();

    // Checkpoint is complete and the seeded context is what the agents saw.
    const cp = checkpointOf(run);
    expect(cp.componentIndex).toBe(hired.blueprint.components.length);
    expect(cp.deliverableId).toBe(deliverable.id);
    expect(cp.agent).toBeUndefined();
    expect(cp.context.instructions).toEqual(["Focus on vector databases"]);
    expect(String(cp.context.job_brief)).toContain(`# Job: ${hired.spec.title}`);
    expect(cp.context.report).toBe(deliverable.content);
    expect(cp.counters.activeMs).toBe(run.durationMs);
    expect(cp.counters.modelCalls).toBe(modelSteps.length);

    // Activity: the run's story in order, with the deliverable linked.
    const types = await activityTypes(t.organization.id, runId);
    expect(types.slice(0, 2)).toEqual(["RUN_QUEUED", "RUN_STARTED"]);
    expect(types).toContain("DELIVERABLE_CREATED");
    expect(types).toContain("EVALUATION_COMPLETED");
    expect(types.at(-1)).toBe("RUN_SUCCEEDED");
    expect(types.filter((x) => x === "TOOL_USED")).toHaveLength(0);
    const succeeded = await db.activityEvent.findFirstOrThrow({ where: { organizationId: t.organization.id, runId, type: "RUN_SUCCEEDED" } });
    expect(succeeded.detail).toContain(deliverable.title);
    expect(succeeded.metadata).toMatchObject({ deliverableId: deliverable.id });

    // Executing a finished run again is a no-op that reports its state.
    const again = await executeRun(runId);
    expect(again).toEqual({ status: "SUCCEEDED", deliverableIds: [deliverable.id] });
    expect((await stepsOf(runId)).length).toBe(steps.length);
  });

  it("runs the same slice whether claimed by the executor loop or inline, and rejects a stranger while RUNNING", async () => {
    const hired = await createHiredWorker(t.organization.id);
    const runId = await enqueue(t, hired);
    expect(await claimNextRun("exec-loop", { organizationId: t.organization.id })).toBe(runId);
    await expect(executeRun(runId, { executorId: "someone-else" })).rejects.toSatisfy((e: unknown) => e instanceof AppError && e.code === "CONFLICT");
    const outcome = await executeRun(runId, { executorId: "exec-loop" });
    expect(outcome.status).toBe("SUCCEEDED");
  });

  it("produces a JSON deliverable from the records directly when the blueprint asks for json", async () => {
    const blueprint = makeBlueprint({
      overrides: { deliverable: { titleTemplate: "{{job_title}} — {{date}}", format: "json", contentKey: "records", dataKey: "records" } },
    });
    const hired = await createHiredWorker(t.organization.id, { blueprint });
    const runId = await enqueue(t, hired);
    const outcome = await executeRun(runId);
    expect(outcome.status).toBe("SUCCEEDED");
    const deliverable = await db.deliverable.findFirstOrThrow({ where: { runId } });
    expect(deliverable.format).toBe("JSON");
    expect(deliverable.title).toMatch(new RegExp(`^${hired.spec.title} — \\d{4}-\\d{2}-\\d{2}$`));
    const parsed = JSON.parse(deliverable.content) as unknown[];
    expect(parsed).toEqual(deliverable.data);
    expect(deliverable.summary).toBe(`${parsed.length} records`);
    // The deliverable exists at the FIRST boundary where its keys are present: right after the collector.
    const steps = await stepsOf(runId);
    const deliverableIndex = steps.findIndex((s) => s.kind === "DELIVERABLE");
    const firstDeterministic = steps.findIndex((s) => s.kind === "DETERMINISTIC");
    expect(deliverableIndex).toBeGreaterThan(0);
    expect(deliverableIndex).toBeLessThan(firstDeterministic);
  });
});

describe("runtime: executeRun — limits and failures", () => {
  let t: TestOrg;
  beforeAll(async () => {
    t = await createTestOrg("rt-limits");
  });
  afterEach(() => {
    vi.restoreAllMocks();
  });
  afterAll(async () => {
    await t.cleanup();
  });

  it("fails with LIMIT_EXCEEDED (no retry) when maxToolCallsPerRun is hit, before creating the extra calls", async () => {
    const blueprint = makeBlueprint({ overrides: { limits: { ...DEFAULT_RUN_LIMITS, maxToolCallsPerRun: 1 } } });
    const hired = await createHiredWorker(t.organization.id, { blueprint });
    const runId = await enqueue(t, hired);

    const outcome = await executeRun(runId);
    expect(outcome.status).toBe("FAILED");
    if (outcome.status !== "FAILED") return;
    expect(outcome.willRetry).toBe(false);
    expect(outcome.error).toMatch(/limit of 1 tool call/);

    const run = await loadRun(runId);
    expect(run).toMatchObject({ status: "FAILED", attempt: 1, lockedBy: null });
    expect(run.error).toBe(outcome.error);
    expect(run.durationMs).toBeGreaterThanOrEqual(0);
    expect(await db.toolCall.count({ where: { runId } })).toBeLessThanOrEqual(1);
    expect(await db.deliverable.count({ where: { runId } })).toBe(0);

    const steps = await stepsOf(runId);
    const error = steps.at(-1);
    expect(error?.kind).toBe("ERROR");
    expect(error?.title).toBe(outcome.error);
    expect(error?.componentId).toBe("collector");
    expect(error?.output).toMatchObject({ code: "LIMIT_EXCEEDED", retryable: false });
    expect(steps.some((s) => ["RUNNING", "PENDING", "WAITING"].includes(s.status))).toBe(false);

    expect(await activityTypes(t.organization.id, runId)).toEqual(["RUN_QUEUED", "RUN_STARTED", "RUN_FAILED"]);
    expect((await db.worker.findUniqueOrThrow({ where: { id: hired.worker.id } })).scoreUpdatedAt).not.toBeNull();
    expect(await executeRun(runId)).toEqual({ status: "FAILED", error: outcome.error, willRetry: false });
  });

  it("fails with LIMIT_EXCEEDED when the cost cap is already exceeded", async () => {
    const blueprint = makeBlueprint({ overrides: { limits: { ...DEFAULT_RUN_LIMITS, maxCostPerRunUsd: 0.000001 } } });
    const hired = await createHiredWorker(t.organization.id, { blueprint });
    const runId = await enqueue(t, hired);
    const outcome = await executeRun(runId);
    expect(outcome).toMatchObject({ status: "FAILED", willRetry: false });
    expect((outcome as { error: string }).error).toMatch(/cost limit/);
  });

  it("re-queues a MODEL_ERROR with backoff, restores the failed component's start, and the retry succeeds without step collisions", async () => {
    const hired = await createHiredWorker(t.organization.id);
    const runId = await enqueue(t, hired);

    // The analyst's first model call hits a provider outage; everything before it (collector + cleaning) is kept.
    const original = llm.generateText;
    const outage = vi.spyOn(llm, "generateText").mockImplementation(async (req, tracking) => {
      if (tracking.runId === runId && isAnalystTurn(req)) {
        outage.mockRestore();
        throw new AppError("MODEL_ERROR", "Anthropic could not complete the request: 503");
      }
      return original(req, tracking);
    });

    const first = await executeRun(runId);
    expect(first).toMatchObject({ status: "FAILED", willRetry: true });
    const queued = await loadRun(runId);
    expect(queued).toMatchObject({ status: "QUEUED", attempt: 2, lockedBy: null, heartbeatAt: null });
    expect(queued.availableAt.getTime()).toBeGreaterThan(Date.now() + 10_000);
    expect(queued.error).toMatch(/503/);
    const cpAfterFirst = checkpointOf(queued);
    expect(cpAfterFirst.componentIndex).toBe(hired.blueprint.components.findIndex((c) => c.id === "analyst"));
    expect(cpAfterFirst.agent).toBeUndefined();
    expect(Array.isArray(cpAfterFirst.context.records)).toBe(true);
    expect(cpAfterFirst.context.insights).toBeUndefined();
    const stepsAfterFirst = await stepsOf(runId);
    expect(stepsAfterFirst.at(-1)?.kind).toBe("ERROR");
    expect(stepsAfterFirst.at(-1)?.componentId).toBe("analyst");
    expect(stepsAfterFirst.at(-2)).toMatchObject({ kind: "MODEL_CALL", status: "FAILED", componentId: "analyst" });
    expect(cpAfterFirst.nextStepIndex).toBe(stepsAfterFirst.length);
    expect(await activityTypes(t.organization.id, runId)).toEqual(["RUN_QUEUED", "RUN_STARTED"]);

    // The executor would wait for availableAt; tests pull it forward and run the second attempt inline.
    await db.run.update({ where: { id: runId }, data: { availableAt: new Date() } });
    const second = await executeRun(runId);
    expect(second.status).toBe("SUCCEEDED");
    const done = await loadRun(runId);
    expect(done).toMatchObject({ status: "SUCCEEDED", attempt: 2, error: null });
    const steps = await stepsOf(runId);
    expect(new Set(steps.map((s) => s.index)).size).toBe(steps.length);
    expect(steps.filter((s) => s.kind === "ERROR")).toHaveLength(1);
    const retried = steps.filter((s) => s.attempt === 2);
    expect(retried.every((s) => s.index >= stepsAfterFirst.length)).toBe(true);
    // The retry re-ran only the analyst onwards: no second collector or cleaning pass.
    expect(retried.filter((s) => s.kind === "TOOL_CALL")).toHaveLength(0);
    expect(retried.filter((s) => s.kind === "DETERMINISTIC").map((s) => s.title)).toEqual(["Compile report"]);
    expect(await db.deliverable.count({ where: { runId } })).toBe(1);
    const cp = checkpointOf(done);
    expect(cp.counters.activeMs).toBe(done.durationMs);
    expect(cp.counters.activeMs).toBeGreaterThanOrEqual(cpAfterFirst.counters.activeMs);
    expect(await activityTypes(t.organization.id, runId)).toEqual(["RUN_QUEUED", "RUN_STARTED", "DELIVERABLE_CREATED", "EVALUATION_COMPLETED", "RUN_SUCCEEDED"]);
  });

  it("fails immediately, without retry, when the version's blueprint no longer parses", async () => {
    const hired = await createHiredWorker(t.organization.id);
    const runId = await enqueue(t, hired);
    await db.workerVersion.update({ where: { id: hired.version.id }, data: { blueprint: toJson({ schemaVersion: 1, components: [] }) } });

    const outcome = await executeRun(runId);
    expect(outcome).toMatchObject({ status: "FAILED", willRetry: false });
    expect((outcome as { error: string }).error).toMatch(/blueprint is invalid/);
    const run = await loadRun(runId);
    expect(run).toMatchObject({ status: "FAILED", attempt: 1, lockedBy: null });
    expect(await activityTypes(t.organization.id, runId)).toEqual(["RUN_QUEUED", "RUN_STARTED", "RUN_FAILED"]);
  });

  it("honours a cancel that lands mid-slice: the executor stops at its next fenced write and writes nothing further", async () => {
    const hired = await createHiredWorker(t.organization.id);
    const runId = await enqueue(t, hired);
    const original = llm.generateText;
    const spy = vi.spyOn(llm, "generateText").mockImplementation(async (req, tracking) => {
      const result = await original(req, tracking);
      if (tracking.runId === runId && isAnalystTurn(req)) {
        spy.mockRestore();
        await cancelRun(t.session, runId); // the user clicks Cancel while the analyst is thinking
      }
      return result;
    });

    expect(await executeRun(runId)).toEqual({ status: "CANCELLED" });
    const run = await loadRun(runId);
    expect(run).toMatchObject({ status: "CANCELLED", lockedBy: null });
    expect(await db.deliverable.count({ where: { runId } })).toBe(0);
    const steps = await stepsOf(runId);
    expect(steps.some((s) => s.kind === "DELIVERABLE" || s.kind === "EVALUATION" || s.kind === "ERROR")).toBe(false);
    expect(steps.some((s) => ["RUNNING", "PENDING", "WAITING"].includes(s.status))).toBe(false);
    // The in-flight analyst step was closed by the cancel, and the zombie slice could not rewrite it afterwards.
    expect(steps.at(-1)).toMatchObject({ kind: "MODEL_CALL", componentId: "analyst", status: "SKIPPED" });
    const types = await activityTypes(t.organization.id, runId);
    expect(types.at(-1)).toBe("RUN_CANCELLED");
    expect(types).not.toContain("RUN_SUCCEEDED");
  });

  it("lets exactly one executor finish a run that was recovered and re-claimed while the first was still working", async () => {
    const hired = await createHiredWorker(t.organization.id);
    const runId = await enqueue(t, hired);
    expect(await claimNextRun("exec-a", { organizationId: t.organization.id })).toBe(runId);

    let takeover: Awaited<ReturnType<typeof executeRun>> | undefined;
    const original = llm.generateText;
    const spy = vi.spyOn(llm, "generateText").mockImplementation(async (req, tracking) => {
      if (tracking.runId === runId && isAnalystTurn(req)) {
        spy.mockRestore();
        // Stale recovery re-queues the run (executor A looks dead) and executor B picks it up and finishes it.
        await db.run.updateMany({ where: { id: runId, status: "RUNNING", lockedBy: "exec-a" }, data: { status: "QUEUED", lockedBy: null, lockedAt: null, heartbeatAt: null, attempt: 2 } });
        takeover = await executeRun(runId, { executorId: "exec-b" });
      }
      return original(req, tracking);
    });

    const a = await executeRun(runId, { executorId: "exec-a" });
    expect(takeover?.status).toBe("SUCCEEDED");
    // A reports the run's final state but wrote none of it.
    expect(a).toEqual(takeover);
    const run = await loadRun(runId);
    expect(run).toMatchObject({ status: "SUCCEEDED", attempt: 2, lockedBy: null });
    expect(await db.deliverable.count({ where: { runId } })).toBe(1);
    expect((await activityTypes(t.organization.id, runId)).filter((x) => x === "RUN_SUCCEEDED")).toHaveLength(1);
    const steps = await stepsOf(runId);
    expect(new Set(steps.map((s) => s.index)).size).toBe(steps.length);
    expect(steps.filter((s) => s.kind === "EVALUATION")).toHaveLength(1);
    // A's in-flight analyst step stays as B closed it; B's own steps carry attempt 2.
    const interrupted = steps.find((s) => s.attempt === 1 && s.kind === "MODEL_CALL" && s.componentId === "analyst");
    expect(interrupted).toMatchObject({ status: "FAILED", error: "interrupted" });
    expect(steps.filter((s) => s.attempt === 2).length).toBeGreaterThan(0);
  });

  it("heartbeats while a slice is running", async () => {
    process.env.EXECUTOR_STALE_LOCK_MS = "1000"; // heartbeat every 250 ms
    try {
      const hired = await createHiredWorker(t.organization.id);
      const runId = await enqueue(t, hired);
      let observed: { before: Date | null; after: Date | null } | undefined;
      const original = llm.generateText;
      const spy = vi.spyOn(llm, "generateText").mockImplementation(async (req, tracking) => {
        if (tracking.runId === runId && isAnalystTurn(req)) {
          spy.mockRestore();
          const before = (await loadRun(runId)).heartbeatAt;
          await new Promise((r) => setTimeout(r, 700));
          observed = { before, after: (await loadRun(runId)).heartbeatAt };
        }
        return original(req, tracking);
      });
      expect((await executeRun(runId)).status).toBe("SUCCEEDED");
      expect(observed?.before).toBeInstanceOf(Date);
      expect(observed?.after?.getTime()).toBeGreaterThan(observed!.before!.getTime());
      // Released with the lease once the run finished.
      expect((await loadRun(runId)).heartbeatAt).toBeNull();
    } finally {
      delete process.env.EXECUTOR_STALE_LOCK_MS;
    }
  });

  it("returns the current state without side effects for runs that cannot be executed", async () => {
    const hired = await createHiredWorker(t.organization.id);
    const runId = await enqueue(t, hired);
    await db.run.update({ where: { id: runId }, data: { status: "CANCELLED", finishedAt: new Date() } });
    expect(await executeRun(runId)).toEqual({ status: "CANCELLED" });
    expect(await stepsOf(runId)).toHaveLength(0);
    await expect(executeRun("run_missing")).rejects.toSatisfy((e: unknown) => e instanceof AppError && e.code === "NOT_FOUND");
  });
});
